### ISSUE TITLE
Examples needed?

### ISSUE THREAD

**Issue by matthew-dean** [neetjn/v-localize#2]
I don't see any examples in the readme of how to actually implement this in `.vue` files. How are elements labeled to be translated?

**Comment by neetjn** [comment]
My apologies, this was an experimental plugin with Vue. I'll definitely go ahead and update the docs as soon as I finish reworking the plugin.

You can localize your elements using the directive `v-localize`. An example,

```js
const localizations =
{
  en: {
    header: {
      title: 'Hello World!'
    },
    body: {
      content: 'Today is the 5th of May.'
    }
  },
  sp: {
    header: {
      title: 'Hola Mundo!'
    },
    body: {
      content: 'Hoy es el cinco de Mayo.'
    }
  }
};

Vue.use(VueLocalize, {
  lang_default: 'en',
  localizations: localizations,
  locale_default: '...'
}); // # install our plugin
```

```html
<h1 v-localize="'header.title'"></h1>
```

We use innerHTML to modify the DOM, so you can include HTML in your localization map. Again, I apologize for the lack of documentation, I've been working on another project.

**Comment by neetjn** [comment]
The new version will support localization with titles and other like attributes.

**Comment by neetjn** [comment]
Version 1.0.3 released. If you have any questions, feel free to re-open. I've added more useful documentation into the README.
