### ISSUE TITLE
 Error in directive localize unbind hook: "ReferenceError: vm is not defined"

### ISSUE THREAD

**Issue by seegodesign** [neetjn/v-localize#37]
1. Describe your issue:
This bug appears in the "unbind" function, when a component containing localized text is hidden with v-if

2. Can you reproduce the issue?
Yes

3. On which browser/OS does the issue appear?
All platforms

4. Which version of v-localize does it affect?
1.2.1

5. How would you tag this issue?
Bug

See: https://jsfiddle.net/seegodesign/yh3mtsa0/4/

**Comment by neetjn** [comment]
Resolved in https://github.com/neetjn/v-localize/pull/38.
---
Remember to star if you find v-localize helpful!
